### ISSUE TITLE
Can't remove show in collection after adding

### ISSUE THREAD

**Issue by snollygolly** [EvilMouseStudios/bloodhound#14]
If you add a show and then try to remove it right away, it tells you that the show isn't in your collection.

**Comment by mikemclaren** [comment]
This no longer seems to be an issue. Closing. :+1:

**Comment by jfeigel** [comment]
Don't be closing my bugs!

**Comment by mikemclaren** [comment]
Under what circumstances is this broken? I'm seeing it working wonderfully.

**Comment by jfeigel** [comment]
I fixed it before, just forgot to close it.

**Comment by mikemclaren** [comment]
:confetti_ball: Kick butt.
