### ISSUE TITLE
Create login page with multiple options.

### ISSUE THREAD

**Issue by mikemclaren** [EvilMouseStudios/bloodhound#39]
Considering we can hook this up to a bunch of different services, we need to create a login page that provides buttons for logging in with various services (like Facebook, Twitter, Github, etc).

Maybe also use this issue to list services we can/should allow people to login with.

**Comment by jfeigel** [comment]
Not sure if it needs to be a separate issue, but we should add `Log Out` too.

**Comment by snollygolly** [comment]
@jfeigel It should.  I'm creating it.

**Comment by snollygolly** [comment]
Created as #42

**Comment by snollygolly** [comment]
Used font-awesome and bootstrap-social to create login buttons for twitter, facebook, and github.  We can easily add more in the future.  I've disabled all but twitter for now.
