### ISSUE TITLE
getListingByID test fails with timeout

### ISSUE THREAD

**Issue by snollygolly** [EvilMouseStudios/bloodhound#45]
```
  2) Search plugin: tv_rage.js should return the proper object for .getListingByID:
     Error: timeout of 2000ms exceeded
```

How to make timeout less?

**Comment by snollygolly** [comment]
I tried running mocha with `--timeout 5000` but it just took longer to fail

**Comment by mikemclaren** [comment]
If you're hitting a timeout, 9/10 times it's because the test is failing for reasons you're not checking against.

**Comment by snollygolly** [comment]
I've removed all the `.to.be.a('type')` tests and it passes successfully.  I've also console logged the type of variables I'm trapping, and they match, but the test still fails.

**Comment by mikemclaren** [comment]
Can you throw up a gist/put the code in the issue?

**Comment by snollygolly** [comment]
https://github.com/snollygolly/bloodhound/blob/master/tests/search-plugins.js#L86-L118

**Comment by mikemclaren** [comment]
It seems like expect().to.be.a() isn't throwing the correct error. It's most likely an issue with Chai not playing well with co-mocha. Meeeh.

However, this is fixed.
