### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by snollygolly** [EvilMouseStudios/bloodhound#52]
The current footer (copyright Evil Mouse Studios) doesn't really adequately describe our project.  I'd really like something prettier that gave a link to the github page, maybe a link to our org's contributors page or something.  I'm not entirely sure.

**Comment by snollygolly** [comment]
Addressed by @JoshSpears3 in https://github.com/EvilMouseStudios/bloodhound/pull/56

Ideally though, I'd like the following changed:
- octocat logo to be grey with darker grey on hover (see github.com for example)
- make the link go to the repository instead of the organization
- make the link open in a new window
- center the octocat in the middle (we'll need the right for badges later I think)

**Comment by JaySpears** [comment]
@snollygolly 

All wanted changed to footer have been added.

**Comment by snollygolly** [comment]
Resolved by @JoshSpears3
