### ISSUE TITLE
Get Capistrano set up and running for deploying to http://bloodhound.tv

### ISSUE THREAD

**Issue by snollygolly** [EvilMouseStudios/bloodhound#54]

**Comment by galenandrew** [comment]
+1

**Comment by snollygolly** [comment]
Resolved by @ozee

Thanks!

**Comment by galenandrew** [comment]
Missing `Capfile` in the implementation.

**Comment by snollygolly** [comment]
Totally doesn't work.  Consider switching to shipit.

**Comment by galenandrew** [comment]
@snollygolly did it just recently stop working or has it never worked? What errors are you getting?

**Comment by snollygolly** [comment]
You know, I don't think it ever worked.  It was complaining about a username and host, but even after I filled those in, I couldn't get it to work.  I just added a solid shipit file to my koa-starter repo, so I'm going to port that over to bloodhound eventually.

**Comment by snollygolly** [comment]
Switched to ShipIt, deployed, celebrated.
